--- #YAML:1.0
name:                Pod-Help
version:             1.00
abstract:            Perl module to automate POD display
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Pod::Perldoc:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - M. Jacob <jacob@j-e-b.net>
